FROM node:25.6.0-slim

RUN apt update && apt install -y --no-install-recommends procps curl ffmpeg && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /tmp/streamtube-videos && chown node:node /tmp/streamtube-videos

WORKDIR /home/node/app

COPY package*.json ./
RUN npm ci

COPY . .

USER node

CMD [ "tail", "-f", "/dev/null" ]
